language: r
cache: packages
branches:
  only:
  - master
  - dev
notifications:
  email:
    recipients:
      - andrew@exegetic.biz
    on_success: always
    on_failure: always
# For test coverage.
r_github_packages:
  - jimhester/covr

before_deploy:
- Rscript inst/hex/logo.R
- Rscript -e 'pkgdown::build_site()'
deploy:
  provider: pages
  github_token: "$GITHUB_TOKEN"
  skip_cleanup: true
  local_dir: docs
  target_branch: gh-pages
  on:
    branches:
      only:
        - master
        - dev

after_success:
  - Rscript -e 'covr::codecov()'