language: r
cache: packages
branches:
  only:
  - master
  - dev
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    recipients:
      - andrew@exegetic.biz
    on_success: always
    on_failure: always
# For test coverage.
r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
